//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PutishestviePoRossii
{
    using System;
    using System.Collections.Generic;
    
    public partial class boat
    {
        public int ID { get; set; }
        public string name { get; set; }
        public string number_of_telephone { get; set; }
        public Nullable<int> ID_client { get; set; }
    
        public virtual client client { get; set; }
    }
}
